### ISSUE TITLE
Feature: Add flag to format unix timestamps into Javascript Date timestamps

### ISSUE THREAD

**Issue by jordond** [worldturtlemedia/darksky-api#20]
Right now the response that comes back from DarkSky will not create the correct date in javascript.  You have to do this:

```typescript
const { dt } = forecast.current
const data = new Date(dt * 1000) 
```

It would be nice to have an optional flag that would convert the response automatically.

Something like:

```typescript
new DarkSky('token', { formatTimestamp: true })
```

**Comment by nschild** [comment]
or even better, provide a wrapper function for dates:

`new DarkSky('token', { formatTimestamp: (timestamp) => timestamp * 1000 })`

`new DarkSky('token', { formatTimestamp: (timestamp) => new Date(timestamp * 1000) })`

`new DarkSky('token', { formatTimestamp: (timestamp) => moment(timestamp * 1000).format('h:mma') })`

**Comment by jordond** [comment]
Closing because of #385
