### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by nschild** [worldturtlemedia/darksky-api#233]
Good work on typing the Darksky API. I recently added this as a dependancy to our apps for the definitions to type-check the response from our internal proxy of the DS data. I am going to ask my contact at DS to look into your repo and maybe feature it or possibly the definitions on their site. It saved me a bunch of time and now I know that the data will be correct. Thanks! Expect a bunch of installs from your NPM repo in the next month or so, when this sprint is released to production.

**Comment by jordond** [comment]
Thanks for taking the time to leave that comment :smile:!  I made this library to use in one of my own personal projects, didn't really expect anyone to really see it.  So thanks for using it!
